//DDE Current Chapters Page
//Focuses on creating links for each email

$w.onReady(function () {

	//Chapters header styling
	const chapters_header = $w("#chapters-header").text;
    $w("#chapters-header").html = `<p style="text-align: center;font-size: 24px;font-family: 'Oswald', sans-serif; font-weight: bold;">${chapters_header}</p>`;

	//Styling constants
	const colorBlue = "#87aade";
	const fontSize = "16px";
	const fontName = "questrial";

	$w("#back").link = "/dde";
	$w("#back").target = "_self";

	//FInd the email from each text element
	$w("#chapters").children.filter(item => item.type === "$w.Text").forEach(element => {
        //Generated by ChatGPT to detect emails using patterns
		const emailRegex = /([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})\b/g;
        
		//If email is found, add its link and change to blue coloring
        if (emailRegex.test(element.text)) {
			//@ts-ignore
            element.html = element.text.replace(emailRegex, (match) => {
                return `<a href="mailto:${match}" style="color: ${colorBlue}; font-family: ${fontName}; font-size: ${fontSize};">${match}</a>`;
            });
        }
    });

});